# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-06-26 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text1', models.CharField(max_length=100)),
                ('Text2', models.CharField(max_length=100)),
            ],
        ),
    ]
